### ISSUE TITLE
[REQUEST] Add env variable to ask for credentials when connecting via noVNC

### ISSUE THREAD

**Issue by SmartPhoneLover** [borgbase/vorta-docker#10]
As the title suggests, I would like to request the addition of an env variable to allow us to configure a password when we enter the Vorta interface through noVNC connection (or VNC.)

Thank you!

**Comment by amfp** [comment]
This is essential!
There are no credentials for the access?

**Comment by Ranbato** [comment]
There is one in the base image I am using.  I'll document it.
