### ISSUE TITLE
Ok if I publish this on Unraid?

### ISSUE THREAD

**Issue by yiveynod** [borgbase/vorta-docker#19]
Hi!

Thanks for a great solution getting Vorta to work in Docker. I've used the container published in Unraids Community Applications for some time with good results. Now it seems though that the author SmartPhoneLover have removed the app and also removed their repository for Unraid apps here on GitHub. 

Here is the support thread they have on Unraid forums https://forums.unraid.net/topic/117021-support-smartphonelover-vorta-gui-for-borg-backup/

I wonder if it would be ok if I republish the app to the Unraid CA App Store? Of course with proper links to you and your work. 

It would be my first time publishing a container, so bare with me if I might ask some stupid questions. I just want this awesome app to keep helping folks using BorgBackup, but with a GUI.

Best regards /Yiveynod

**Comment by Ranbato** [comment]
Yes, that is fine. Good luck!MarkOn Sep 14, 2023, at 11:56 PM, Yivey Nod ***@***.***> wrote:﻿
Hi!
Thanks for a great solution getting Vorta to work in Docker. I've used the container published in Unraids Community Applications for some time with good results. Now it seems though that the author SmartPhoneLover have removed the app and also removed their repository for Unraid apps here on GitHub.
Here is the support thread they have on Unraid forums https://forums.unraid.net/topic/117021-support-smartphonelover-vorta-gui-for-borg-backup/
I wonder if it would be ok if I republish the app to the Unraid CA App Store? Of course with proper links to you and your work.
It would be my first time publishing a container, so bare with me if I might ask some stupid questions. I just want this awesome app to keep helping folks using BorgBackup, but with a GUI.
Best regards /Yiveynod
