### ISSUE TITLE
Access to the host-system

### ISSUE THREAD

**Issue by Mitch187** [borgbase/vorta-docker#21]
Hi,

sorry to post here. I know this is not an issue, because i am the problem, i think.

i have installed the vorta-docker to a host-system:
`docker run -d -it -p 5901:5800 -p 5900:5900 --name=Vorta-BorgBackup --hostname=vorta-borgbackup --restart=always -v vorta_data:/config  ghcr.io/borgbase/vorta-docker:latest
`

I can access to the Port 5901 via http....nice

I can configure a remote host....nice, too.

But i can't access to the filesystem of the host-system. i can only backup the file system of the docker-container.

What can i do?

Best Regards,
Mitch

**Comment by Ranbato** [comment]
You need to add a volume mount for the host system and, potentially, a mount for the destination.  Something along the lines of `-v /hostvolume1:/data:ro -v /volumeUSB1/:/destination` and then backup from `/data` to `/destination`
