### ISSUE TITLE
Different Repo, different SSH keys, 'list command' not working

### ISSUE THREAD

**Issue by wokkieman** [borgbase/vorta-docker#22]
I've added 3 existing repo's (1 profile) and specified the ssh key to use in the 'advanced' section, but it looks like it isn't working when trying to list archives. The error is that the folder is not allowed, which basically says wrong key.

if I then change the key in the main window (just above the compression key select box) to the right one (same as indicated in the advanced section), then I can list my archives.

The strange this is that the correct ssh key (the one from advanced section) looks to be used to query the size and deduped size. They are nicely updating

**Comment by Ranbato** [comment]
Is this specific to running Vorta in Docker or does the same thing happen when you run it standalone?

**Comment by wokkieman** [comment]
I've only tried it in Docker. It's a headless server. Borg via cli works fine

**Comment by Ranbato** [comment]
I suspect it is an issue in Vorta itself then.  There are [22 open issues](https://github.com/borgbase/vorta/issues?q=is%3Aissue+ssh+is%3Aopen++list) that have "ssh" and "list" in them.  If none of them are the same, create an issue there and link it please.

**Comment by wokkieman** [comment]
logged an issue: https://github.com/borgbase/vorta/issues/1975
