### ISSUE TITLE
Add fuse support?

### ISSUE THREAD

**Issue by Sdub76** [borgbase/vorta-docker#6]
I'm not able to mount a backup to extract files from an archive because this docker doesn't include FUSE support.  Would be a nice addition, since Vorta is only semi-useful without the ability to restore.

**Comment by Ranbato** [comment]
I have started looking into this, but I can't test it locally as my NAS doesn't support FUSE.  Happy to have someone try out an image though.
Also, it looks like it will require granting sysadmin privileges to the Vorta docker container.

**Comment by Ranbato** [comment]
OK, I have it working locally using `--privileged` but that is a REALLY BAD IDEA.
I also have it working with `--cap-add SYS_ADMIN --security-opt apparmor=unconfined` which is much less risky but not fantastic.

It sounds to me like the exact parameter required will depend on the kernel version you are running on your Docker host.

Would like to have a few people try it before I push it out generally.

**Comment by Sdub76** [comment]
Do you have a branch I can pull to test?  

It might not be a showstopper to use privileged if you only enable the option in the relatively rare case you need to restore something.

**Comment by m3nu** [comment]
Awesome! When you're done, open a PR, so the changes are easier to see.
